# Stage 1: Build the application
FROM node:22-alpine3.19 AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package.json package-lock.json ./

RUN npm install

# Install dependencies
RUN npm ci

# Copy the rest of the application source code
COPY . ./

# Build the application
RUN npm run build

# Stage 2: Serve the application with Node
FROM node:22-alpine3.19

# Set working directory
WORKDIR /app

# Copy the built files from the build stage
COPY --from=build /app/build ./build

# Copy package.json and package-lock.json for dependency installation
COPY package.json package-lock.json ./

RUN npm install

# Install only production dependencies
RUN npm ci --only=production

# Copy the rest of the application source code (for server and configuration)
COPY . ./

# Set environment variables
ENV NODE_ENV="production"
ENV REACT_APP_DEVELOPMENT="LOCAL|DEV|TEST|PROD"
ENV REACT_APP_ISM_API_BASE_URL=""
ENV REACT_APP_FIREBASE_API_KEY=""
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=""
ENV REACT_APP_FIREBASE_PROJECT_ID=""
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=""
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=""
ENV REACT_APP_FIREBASE_APP_ID=""

# Expose port (if your app runs on a specific port, e.g., 3000)
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
