#!/bin/sh

# Replace placeholders in JS files with environment variables
for file in /usr/share/nginx/html/static/js/*.js; do
  sed -i 's|REACT_APP_DEVELOPMENT_PLACEHOLDER|'${REACT_APP_DEVELOPMENT}'|g' $file
  sed -i 's|REACT_APP_ISM_API_BASE_URL_PLACEHOLDER|'${REACT_APP_ISM_API_BASE_URL}'|g' $file
  sed -i 's|REACT_APP_FIREBASE_API_KEY_PLACEHOLDER|'${REACT_APP_FIREBASE_API_KEY}'|g' $file
  sed -i 's|REACT_APP_FIREBASE_AUTH_DOMAIN_PLACEHOLDER|'${REACT_APP_FIREBASE_AUTH_DOMAIN}'|g' $file
  sed -i 's|REACT_APP_FIREBASE_PROJECT_ID_PLACEHOLDER|'${REACT_APP_FIREBASE_PROJECT_ID}'|g' $file
  sed -i 's|REACT_APP_FIREBASE_STORAGE_BUCKET_PLACEHOLDER|'${REACT_APP_FIREBASE_STORAGE_BUCKET}'|g' $file
  sed -i 's|REACT_APP_FIREBASE_MESSAGING_SENDER_ID_PLACEHOLDER|'${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}'|g' $file
  sed -i 's|REACT_APP_FIREBASE_APP_ID_PLACEHOLDER|'${REACT_APP_FIREBASE_APP_ID}'|g' $file
done

# Start Nginx
exec "$@"
