apiVersion: apps/v1
kind: Deployment
metadata:
  name: alethic-ism-ui-deployment
  namespace: alethic
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: alethic-ism-ui
  template:
    metadata:
      labels:
        app: alethic-ism-ui
    spec:
      containers:
      - name: alethic-ism-ui
        image: krasaee/alethic-ism-ui:0680191a526f10e2d714c9e50aa98a0570c8b039
        env:
          - name: REACT_APP_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_ENVIRONMENT
          - name: REACT_APP_ISM_API_BASE_URL
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_ISM_API_BASE_URL
          - name: REACT_APP_API_KEY
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_API_KEY
          - name: REACT_APP_AUTH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_AUTH_DOMAIN
          - name: REACT_APP_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_PROJECT_ID
          - name: REACT_APP_STORAGE_BUCKET
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_STORAGE_BUCKET
          - name: REACT_APP_MESSAGING_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_MESSAGING_SENDER_ID
          - name: REACT_APP_APP_ID
            valueFrom:
              secretKeyRef:
                name: alethic-ism-ui-secret
                key: REACT_APP_APP_ID
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
